spring:
  datasource:
    url: jdbc:mysql://localhost/rise?serverTimezone=UTC
    username: gebruiker
    password: pw123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9081