spring:
  datasource:
    url: jdbc:mysql://localhost/rise?serverTimezone=UTC
    username: brainstorm13user
    password: user123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 9081